config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  resources :books

  get 'books/index'
  get 'books/new'
  get 'books/edit'
  get 'books/show'
  get 'all_books' => 'books#all_books'
  get 'bestsellers' => 'books#bestsellers'
  get 'borrow' => 'books#borrow'
  get 'user_borrows' => 'borrowed_books#user_borrowed_books'
  get 'borrows' => 'borrowed_books#all_borrowed_books'
  post 'user_return' => 'borrowed_books#user_return_book'
  post 'all_return' => 'borrowed_books#return_book'

  root 'books#index'

end

app/models/book.rb
class Book < ActiveRecord::Base
	has_many :borrowed_books
	has_many :users, through: :borrowed_books
	belongs_to :category
	validates_presence_of :name, :isbn,:author, :description, :quantity, :surcharge_fee
	mount_uploader :image, PictureUploader
end

app/models/borrowed_book.rb
class BorrowedBook < ActiveRecord::Base
	belongs_to :user
	belongs_to :book
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :books
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :borrowed_books
  has_many :books, through: :borrowed_books
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, :omniauth_providers => [:facebook]       

  #used to grab user details from Facebook when the user signs in
  def self.from_omniauth(auth)
	  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
	    user.email = auth.info.email
	    user.password = Devise.friendly_token[0,20]
	    user.name = auth.info.name   # assuming the user model has a name
	    user.image = auth.info.image # assuming the user model has an image
	  end
  end
  #used to copy data from the session if the user is initialized before signup
  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	require 'rest-client'
	before_action :admin, only: [:new, :edit]
	def new
		@book = Book.new
	end

	#function to create a new book
	def create
		@book = Book.new(book_params)
		respond_to do |format|
			if @book.save
				format.html{redirect_to @book}
				format.json{render :show, status: :created, location: @book}
			else
				format.html{render :new}
				format.json{render json: @book.errors, status: :unprocessible_entity}
			end
		end
	end

	def edit
		@book = Book.find_by_id(params[:id])
	end

	def update
		@book = Book.find_by_id(params[:id])
		respond_to do |format|
			if @book.update_attributes(book_params)
				redirect_to @book
			else
				render 'edit'
			end
		end
	end

	def show
		@book = Book.find_by_id(params[:id])
	end

	def index
		@books = Book.all.limit(2)
	end

	def all_books
		@books = Book.all
	end

	#initial implementation for borrow
	# doesn't check if a user has borrowed a particular book before
	# add that feature later
	def borrow
		@book = Book.find(params[:book_id])
		if user_signed_in?
			if(!BorrowedBook.exists?({user_id: current_user.id, book_id: @book.id}))
				if (@book.isAvailable && @book.quantity >= 1)
					@book.decrement!(:quantity, 1)
					if(@book.quantity == 0)
						@book.update_attributes(isAvailable:false)
					end
					current_user.borrowed_books.create(book: @book)
					BorrowedBook.last.update_attributes(return_date: BorrowedBook.last.created_at + 7.days)
					redirect_to @book
					flash[:success] = "Yaay! You've borrowed a book! Make sure you return it when due"
				else
					flash[:error] = "Book isn't available"
				end
			else
				redirect_to @book
				flash[:warning] = "You've borrowed this book before"
			end
		else
			redirect_to new_user_session_path
		end
	end

	def bestsellers
		url = 'https://api.nytimes.com/svc/books/v3/lists/best-sellers/history.json'
		response = RestClient.get(url, {params: {"api-key" => "e8d78bf70d704f218a49195e256d25b2"}})
		@books =  JSON.parse(response.body)
	end

	def destroy
		Book.find(params[:id]).destroy
  		flash[:success] = "Book deleted"
  		redirect_to root_url
	end

	private
	def book_params
	  params.require(:book).permit(:name, :isbn, :author, :description, :quantity, :surcharge_fee, :category_id, :image)
	end

	def admin
		if(!current_user.isAdmin)
			redirect_to root_path
		end
	end
end

app/controllers/borrowed_books_controller.rb
#This class holds actions for returning all borrowed books
#, along with the user that borrowed it
# Consider putting actions for borrow and return here,
# to de-congest the Books controller
class BorrowedBooksController < ApplicationController
	#return books borrowed by a particular user
	def user_borrowed_books
		@books = BorrowedBook.includes(:book, :user).where("user_id = ?", current_user.id).all
	end

	#return all borrowed books and the user that borrowed them
	def all_borrowed_books
		#use includes to join the borrowed_books, books, and users tables
		#includes takes in the model names in singular forms
		# I think joins uses the plural forms for the table names passes as parameters
		# to access any element of the books/ users tables in the views, do:
		# @iteration_variable.book.property or @iteration_variable.user.property 
		@books = BorrowedBook.includes(:book, :user)
	end

	def user_return_book
		@book = BorrowedBook.where("user_id = ? and book_id = ? and \"userHasReturned\" = ?", current_user.id, params[:book_id], false).first

		@book.update_attributes(userHasReturned: true)
		redirect_to user_borrows_path
	end

	def return_book
		@returning_book = Book.find(params[:book_id])
		@returning_book.increment!(:quantity, 1)
		if(@returning_book.quantity == 1)
			@returning_book.update_attributes(isAvailable: false)
		end
		@book = BorrowedBook.where("user_id = ? and book_id = ? and \"userHasReturned\" = ?", params[:user_id], params[:book_id], true).first
		@book.update_attributes(isReturned: true)
		redirect_to borrows_path
	end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
	def facebook
			# You need to implement the method below in your model (e.g. app/models/user.rb)
	    @user = User.from_omniauth(request.env["omniauth.auth"])

	    if @user.persisted?
	      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
	      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
	    else
	      session["devise.facebook_data"] = request.env["omniauth.auth"]
	      redirect_to new_user_registration_url
	    end
	end

	def failure
		redirect_to root_path
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/borrowed_books_helper.rb
module BorrowedBooksHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/views/books/_books.html.erb
<div class="section text-center">
      <div class="container">
        <div class="row">
          <% @books.each do |book| %>
          	
	          <div class="col-md-6">
	          <% if book.image_url.nil? %>  
		          <%= image_tag("Sasuke-Shippuden-uchiha-sasuke-22662093-1280-720.jpg", size: '600x500', class: 'img-responsive img-thumbnail') %>
		       <% else %>
		       		<%= image_tag(book.image_url(:thumb), size: '600x500', class: 'img-responsive img-thumbnail') %>
		       	<% end %>
		            <h1><%= link_to book.name, book_path(book) %></h1>
	            <p></p>
	            <p><%= book.description %></p>
	            <p></p>
	          </div>
	         
   		  <% end %>
        </div>
      </div>
</div>

app/views/books/all_books.html.erb
<div class="section">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="page-header">
              <h1>All Current Books
              </h1>
            </div>
          </div>
        </div>
      </div>
    </div>
<%= render 'books/books' %>

app/views/books/bestsellers.html.erb
<div class="section text-center">
      <div class="container">
        <div class="row">
	<% @books["results"].each do |book| %>
	          	
	  <div class="col-md-6">
	    
	  <%= image_tag("Sasuke-Shippuden-uchiha-sasuke-22662093-1280-720.jpg", size: '600x500', class: 'img-responsive img-thumbnail') %>
	    <span style="font-size: 18px; font-weight: bold">Title</span>: <%= book["title"]%>
	    <p>Description: <%= book["description"] %></p>
	    <p>Author: <%= book["author"] %></p>
	    <p></p>
	  </div>
		         
	<% end %>
	</div>
  </div>
</div>

app/views/books/edit.html.erb
<%= form_for @book do |f|%>
	<%= f.label :name %>
	<%= f.text_field :name, class: 'form-control' %>

	<%= f.label :isbn %>
	<%= f.text_field :isbn, class: 'form-control' %>

	<%= f.label :author %>
	<%= f.text_field :author, class: 'form-control' %>

	<%= f.label :description %>
	<%= f.text_field :description, class: 'form-control' %>

	<%= f.label :quantity %>
	<%= f.number_field :quantity, class: 'form-control' %>

	<%= f.label :surcharge_fee %>
	<%= f.number_field :surcharge_fee, class: 'form-control' %>

	<%= f.submit "Save", class: 'btn btn-primary' %>

<% end %>

app/views/books/index.html.erb
<div class="section">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="page-header">
              <h1>Some featured books
              </h1>
            </div>
          </div>
        </div>
      </div>
    </div>
<div class="section text-center">
      <div class="container">
        <div class="row">
          <% @books.each do |book| %>
          	
	          <div class="col-md-6">
	            
	          <%= image_tag("Sasuke-Shippuden-uchiha-sasuke-22662093-1280-720.jpg", size: '600x500', class: 'img-responsive img-thumbnail') %>
	            <h1><%= book.name %></h1>
	            <p></p>
	            <p><%= book.description %></p>
	            <p></p>
	          </div>
	         
   		  <% end %>
        </div>
      </div>
    </div>

app/views/books/new.html.erb
      <div class="container">
        <div class="row">	
	        <%= form_for @book,:html =>  { :multipart => true } do |f|%>
				<%= f.label :name %>
				<%= f.text_field :name, class: 'form-control' %>

				<%= f.label :isbn %>
				<%= f.text_field :isbn, class: 'form-control' %>

				<%= f.label :author %>
				<%= f.text_field :author, class: 'form-control' %>

				<%= f.label :description %>
				<%= f.text_field :description, class: 'form-control' %>

				<%= f.label :quantity %>
				<%= f.number_field :quantity, class: 'form-control' %>

				<%= f.label :surcharge_fee %>
				<%= f.number_field :surcharge_fee, class: 'form-control' %>
				<br/>
				<%= f.collection_select(:category_id, Category.all, :id, :name) %>
				<br/> <br/>
				<p>
					<%= f.file_field :image,class: "filestyle", value: "Book Image", accept: 'image/jpeg,image/gif,image/png'%>
					<%= f.hidden_field :image_cache %>
				</p>

			<!--  -->

				<%= f.submit "Save", class: 'btn btn-primary' %>

		<% end %>
	  </div>
	</div>  

app/views/books/show.html.erb
<div class="section">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="page-header">
              <h1><%= @book.name %>
              </h1>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="section">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <% if @book.image_url.nil? %>  
              <%= image_tag("Sasuke-Shippuden-uchiha-sasuke-22662093-1280-720.jpg", size: '600x500', class: 'img-responsive img-thumbnail') %>
           <% else %>
              <%= image_tag(@book.image_url, class: 'img-responsive img-thumbnail') %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="section">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <p>Description: <%= @book.description %></p>
            <p>ISBN: <%= @book.isbn %></p>
            <p>Author: <%= @book.author %></p>
            <p>Quantity: <%= @book.quantity %></p>
            <% if @book.isAvailable %>
	            <%= link_to "Borrow this book", borrow_path(book_id: @book.id) , class: 'btn btn-lg btn-success'%>
	        <% else %>
	        	<a class="btn btn-lg btn-danger">This book is currently unavailable</a>
	        <% end %>
          </div>
        </div>
      </div>
    </div>

app/views/borrowed_books/_all_borrowed_books.html.erb
<div class="section">
      <div class="container">
        <div class="row">
        <% @books.each do |book| %>
          <div class="col-md-4">
            <%= image_tag("Sasuke-Shippuden-uchiha-sasuke-22662093-1280-720.jpg", size: '600x500', class: 'img-responsive') %>
            <h2><%= book.book.name %></h2>
            Author: <%= book.book.author %> <br/>
            <!-- So, to access the return day field, I iterate over the books.borrowed books collection -->
            Return Date: <%= book.return_date.to_formatted_s(:long) %><br/>
            Borrowed by: <%= book.user.email %> <br/>

            <% if book.userHasReturned && !book.isReturned && DateTime.now <= book.return_date%>
              <%= button_to "Complete Return", all_return_path(book_id: book.book.id, user_id: book.user.id) %> <br/> <br/>
            <% elsif book.userHasReturned && !book.isReturned && DateTime.now > book.return_date
               %>
               <p>Hey, <%= book.user.email %> is defaulting on his borrowed book. Just to remind you that they're to pay <%= book.book.surcharge_fee %> when the return the book</p>
               <%= button_to "Complete Return", all_return_path(book_id: book.book.id, user_id: book.user.id) %> <br/> <br/>
            <% else %>
              <p style="color: green">Book has been returned</p>
            <% end %>
          </div>
        <% end %>
        </div>
      </div>
    </div>

app/views/borrowed_books/_borrowed_books.html.erb
<div class="section">
      <div class="container">
        <div class="row">
        <% @books.each do |book| %>
          <div class="col-md-4">
            <%= image_tag("Sasuke-Shippuden-uchiha-sasuke-22662093-1280-720.jpg", size: '600x500', class: 'img-responsive') %>
            <h2><%= book.book.name %></h2>
            Author: <%= book.book.author %> <br/>
            <!-- So, to access the return day field, I iterate over the books.borrowed books collection -->
            Return Date: <%= book.return_date.to_formatted_s(:long) %><br/>
            Borrowed by: <%= book.user.email %> <br/>

            <% if !book.userHasReturned && DateTime.now <= book.return_date %>

              <%= button_to "Return book", user_return_path(book_id: book.book.id) %> <br/>
  
            <% elsif !book.userHasReturned && DateTime.now > book.return_date %>

              <p style="color:red"> You'll be paying a surcharge fee of <%= book.book.surcharge_fee %> for a late return. Try to do better next time </p>

            <%= button_to "Return book", user_return_path(book_id: book.book.id) %> <br/>

          <% else %>

            <p style="color:green"> Yay! You've returned this book </p> <br/>

          <% end %>
        </div>
        <% end %>
        </div>
      </div>
    </div>

app/views/borrowed_books/all_borrowed_books.html.erb
<%= render 'borrowed_books/all_borrowed_books' %>

app/views/borrowed_books/user_borrowed_books.html.erb
<%= render 'borrowed_books/borrowed_books' %>

app/views/layouts/_borrowed_books.html.erb
<li>
  <%= link_to "Add A Book", new_book_path %>
</li>
<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
    aria-expanded="false">Borrowed Books<i class="fa fa-caret-down"></i></a>
    <ul class="dropdown-menu" role="menu">
      <li>
        <%= link_to "Borrowed Books", user_borrows_path %>
      </li>
      <li>
        <%= link_to "All Borrowed Books", borrows_path %>
      </li>
  </li>

app/views/layouts/_footer.html.erb
<footer class="section section-primary">
      <div class="container">
        <div class="row">
          <div class="col-sm-6">
            <h1>Footer header</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipisici elit,
              <br>sed eiusmod tempor incidunt ut labore et dolore magna aliqua.
              <br>Ut enim ad minim veniam, quis nostrud</p>
          </div>
          <div class="col-sm-6">
            <p class="text-info text-right">
              <br>
              <br>
            </p>
            <div class="row">
              <div class="col-md-12 hidden-lg hidden-md hidden-sm text-left">
                <a href="#"><i class="fa fa-3x fa-fw fa-instagram text-inverse"></i></a>
                <a href="#"><i class="fa fa-3x fa-fw fa-twitter text-inverse"></i></a>
                <a href="#"><i class="fa fa-3x fa-fw fa-facebook text-inverse"></i></a>
                <a href="#"><i class="fa fa-3x fa-fw fa-github text-inverse"></i></a>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12 hidden-xs text-right">
                <a href="#"><i class="fa fa-3x fa-fw fa-instagram text-inverse"></i></a>
                <a href="#"><i class="fa fa-3x fa-fw fa-twitter text-inverse"></i></a>
                <a href="#"><i class="fa fa-3x fa-fw fa-facebook text-inverse"></i></a>
                <a href="#"><i class="fa fa-3x fa-fw fa-github text-inverse"></i></a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </footer>

app/views/layouts/_header.html.erb
<div class="cover">
      <div class="navbar navbar-default">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-ex-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#"><span>Brand</span></a>
          </div>
          <div class="collapse navbar-collapse" id="navbar-ex-collapse">
            <ul class="nav navbar-nav navbar-right">
              <li class="active">
                  <%= link_to "Home", root_path %>
              </li>
              <li>
                  <%= link_to "Books", '#' %>
              </li>
              <% if !user_signed_in? %>
                  <li>
                      <%= link_to "Login", new_user_session_path %>
                  </li>
              <% else %>
                  <li>
                      <%= link_to "Logout", destroy_user_session_path, method: :delete %>
                  </li>
              <% end %>
             </ul>
          </div>
        </div>
      </div>
      <div class="cover-image" style="background-image : url('https://unsplash.imgix.net/photo-1423683249427-8ca22bd873e0?w=1024&amp;q=50&amp;fm=jpg&amp;s=5e57c661d0f772ce269188a6f5325708')"></div>
      <div class="container">
        <div class="row">
          <div class="col-md-12 text-center">
            <h1 contenteditable="true" class="text-muted">Kachi's Library</h1>
            <p class="lead text-center">Lorem ipsum dolor sit amet, consectetur adipisici eli.</p>
            <br>
            <br>
            <a class="btn btn-info btn-lg">Click me</a>
          </div>
        </div>
      </div>
</div>

app/views/layouts/_mini_header.html.erb
<div class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-ex-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#"><span>Library</span></a>
                </div>
                <div class="collapse navbar-collapse" id="navbar-ex-collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li class="active">
                            <%= link_to "Home", root_path %>
                        </li>
                        <li>
                            <%= link_to "Books", all_books_path %>
                        </li>
                        <% if !user_signed_in? %>
                            <li>
                                <%= link_to "Login", new_user_session_path %>
                            </li>
                        <% else %>
                            <% if !current_user.isAdmin %>
                            <li>  
                                <%= link_to "Borrowed Books", user_borrows_path %>
                            </li>
                            <li>
                                <%= link_to "Add A Book", new_book_path %>
                            </li>
                            <% else %>
                              <%= render 'layouts/borrowed_books' %>
                            <% end %>
                            <li>
                                <%= link_to "Logout", destroy_user_session_path, method: :delete %>
                            </li>
                        <% end %>
                    </ul>
                </div>
            </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Library</title>
  <link href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.min.css"
    rel="stylesheet" type="text/css">
    <link href="http://pingendo.github.io/pingendo-bootstrap/themes/default/bootstrap.css"
    rel="stylesheet" type="text/css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script type="text/javascript" src="https://cdn.jsdelivr.net/bootstrap.filestyle/1.1.0/js/bootstrap-filestyle.min.js"> </script>
  <%= csrf_meta_tags %>
</head>
<body data-spy="scroll">
	<%= render 'layouts/mini_header' %>
		<% flash.each do |message_type, message| %>
			<div class ="alert alert-<%=message_type%>"><%= message %></div>
		<% end %>
	

<%= yield %>

<%= render 'layouts/footer' %>

</body>
</html>